# Generated by Django 4.1.6 on 2023-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.CharField(choices=[('R', 'Regular'), ('A', 'Admin')], max_length=1),
        ),
    ]
